pro_stages_accueil:
    path: /accueil
    controller: App\Controller\ProStagesController::index

pro_stages_entreprise:
    path: /entreprise
    controller: App\Controller\ProStagesController::entreprise

pro_stages_formation:
    path: /formation
    controller: App\Controller\ProStagesController::formation

pro_stages_stage:
    path: /stage/{id}
    controller: App\Controller\ProStagesController::stage

pro_stages_formationStage:
    path: /formation/{id}
    controller: App\Controller\ProStagesController::formationStages

pro_stages_entrepriseStage:
    path: /entreprise/{id}
    controller: App\Controller\ProStagesController::entrepriseStages
